version: '3.8' # Specifies the Docker Compose file format version

services:
  backend: # Renamed service for clarity (optional)
    build:
      context: . # Use the current directory for build context
      dockerfile: Dockerfile # Explicitly specify the Dockerfile
      args: # Pass build arguments if needed (e.g., for different ports)
        BACKEND_PORT: 5001
        FLASK_DEBUG: true
    env_file:
      - .env # Load GEMINI_API_KEY and potentially other secrets
    ports:
      # Map host port 5001 to the container port defined by BACKEND_PORT (default 5001)
      - "5001:${BACKEND_PORT:-5001}"
    volumes:
      # Mount the local backend code into the container for live updates
      - ./backend:/app/backend
      # Mount the local Next.js static output (if needed for testing)
      # This assumes app.py in dev mode looks for it in /app/out
      - ./out:/app/out
    # environment:
      # FLASK_DEBUG, BACKEND_HOST, BACKEND_PORT are now set in Dockerfile ENV
      # GEMINI_API_KEY should be loaded from .env via env_file
    command: flask run --host=0.0.0.0 --port=5001 --debug # Optional: Explicit command override
    restart: unless-stopped
